### PR TITLE
#181339525 On successful registration, users should receive a JWT

### PR DESCRIPTION
**Pull request by Tsa2341**
### What does this PR do?

- This PR adds user registration implementation with passport.js and JWT

### Description of Task to be completed?

- user register with email and password
- user credentials are hashed and stored in the database
- user receives a token after registration
- use passport.js in the registration
- also validate the user inputs

### How should this be manually tested?

- clone this [repo](https://github.com/atlp-rwanda/cabal-bn-be/) and checkout to [this](https://github.com/atlp-rwanda/cabal-bn-be/tree/feature/%23181339525-user-registration-with-jwt) branch

- run yarn install and also add the .env file copied from .env.sample
- run yarn run dbmigrate:all to instantiate the DB
- open postman use this URL(http://localhost:3000/api/v1/user/register)
- enter an email and password
- you can also enter the first_name, last_name, occupation, or bio
- refer to the picture at the bottom for all the other fields

- it should be in JSON format

- for testing run yarn run test

### What are the relevant pivotal tracker stories?

[#23181339525](https://www.pivotaltracker.com/n/projects/2555280)

### Screenshots (if appropriate)

Screenshot (14)

Screenshot (17)

Screenshot (18)

### CODE REVIEW

**Review by Gabin-ishimwe — APPROVED** [review]

**Review by Eli250 — DISMISSED** [review]
Good

**Review by Eli250 — CHANGES_REQUESTED** [review]
There is conflict in your PR.Resolve them.

**Comment by tuyizerejean** [comment]
I can see that you did not add the attribute you still have that for tomorrow

**Comment by Tsa2341** [comment]
I added just forgot to update the PR description. 
Finished now you can see the fields.

**Review by tuyizerejean — APPROVED** [review]

**Review by Eli250 — APPROVED** [review]

**Review by Eli250 — CHANGES_REQUESTED** [review]
There is conflicts.

**Review by Eli250 — APPROVED** [review]
Approved

**Comment by ncutixavier** [comment]
Your build has failed

**Pull request merged**
