### PR TITLE
#181339523 deploy backend application  on heroku

### PR DESCRIPTION
**Pull request by Gabin-ishimwe**
### What does this PR do?
i deployed our backend application on heroku
### Description of Task to be completed?
adding more routes to our backend application
### How should this be manually tested
open this route: [home route](https://staging-bare-chore-1813-tuu3rw.herokuapp.com/api/v1/home)
### Any background context needed?
heroku credentials:

- email: **cabalbarefoot@gmail.com**
- password: **Cabal@barefoot7**
- application is staged on heroku you can check it out on this link: [staged app on heroku](https://dashboard.heroku.com/pipelines/0cdb65af-2218-444a-ab57-9db6bdcd9a17)

### What are the relevant pivotal tracker stories?
[#181339523](https://www.pivotaltracker.com/n/projects/2555280)
### Questions:

### CODE REVIEW

**Review by Eli250 — COMMENTED** [review]
Looks good. Share credentials for the Heroku app, we are going to connect the database.

**Comment by Gabin-ishimwe** [comment]
> Looks good. Share credentials for the Heroku app, we are going to connect the database.

credentials added in the PR

**Review by Eli250 — APPROVED** [review]

**Comment by tuyizerejean** [comment]
I can see that there  is a conflict

**Comment by tuyizerejean** [comment]
Resolve the conflict

**Review by Code-250 — APPROVED** [review]

**Comment by Code-250** [comment]
you have a conflict in your package.json please fix it

**Pull request closed without merging**
